# Generated by Django 5.2 on 2025-05-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeartUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=55)),
                ("age", models.IntegerField()),
                ("sex", models.IntegerField()),
                ("cp", models.IntegerField()),
                ("trestbps", models.IntegerField()),
                ("restecg", models.IntegerField()),
                ("thalach", models.IntegerField()),
                ("exang", models.IntegerField()),
                ("oldpeak", models.FloatField()),
                ("slope", models.IntegerField()),
                ("ca", models.IntegerField()),
                ("thal", models.IntegerField()),
                ("dial", models.IntegerField()),
            ],
        ),
    ]
